-- MySQL Script generated by MySQL Workbench
-- Mon May 15 12:15:14 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema f1History
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema f1History
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `f1History` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `f1History` ;

-- -----------------------------------------------------
-- Table `f1History`.`log_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `f1History`.`log_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `cognom` VARCHAR(45) NULL,
  `mail` VARCHAR(50) NULL COMMENT 'Datos del usuario y datos para iniciar sesión en el sistema, con ciertos privilegios dependiendo de su rol',
  `password` VARCHAR(32) NULL,
  `data_naixement` DATE NULL,
  `rol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `f1History`.`forum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `f1History`.`forum` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `missatge` VARCHAR(250) NULL,
  `moderat` ENUM('Si', 'No') NULL,
  `log_user_id` INT NOT NULL COMMENT 'Tabla que almacenará los comentarios de cada usuario en el foro, Si en la columna moderated el valor es Y los comentarios serán mostrados en el foro',
  PRIMARY KEY (`id`),
  INDEX `fk_forum_log_user1_idx` (`log_user_id` ASC),
  CONSTRAINT `fk_forum_log_user1`
    FOREIGN KEY (`log_user_id`)
    REFERENCES `f1History`.`log_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `f1History`.`producte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `f1History`.`producte` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NULL,
  `descripcio` VARCHAR(500) NULL,
  `preu` DECIMAL(5,2) NULL,
  `stock` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `f1History`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `f1History`.`carrito` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `log_user_id` INT NOT NULL,
  `preuTotal` DECIMAL(5,2) NULL,
  `dataCompra` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cart_log_user1_idx` (`log_user_id` ASC),
  CONSTRAINT `fk_cart_log_user1`
    FOREIGN KEY (`log_user_id`)
    REFERENCES `f1History`.`log_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `f1History`.`scuderia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `f1History`.`scuderia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `companyName` VARCHAR(50) NULL,
  `teamName` VARCHAR(50) NULL,
  `chassisName` VARCHAR(50) NULL,
  `engineName` VARCHAR(50) NULL,
  `central` VARCHAR(70) NULL,
  `foundation` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `f1History`.`pilot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `f1History`.`pilot` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NULL,
  `sigles` VARCHAR(3) NULL,
  `data_naixement` VARCHAR(45) NULL,
  `pes` INT NULL,
  `altura` DECIMAL(4,2) NULL,
  `punts_totals` INT NULL,
  `carreres_totals` INT NULL,
  `primera_escuderia` VARCHAR(45) NULL,
  `nacionalitat` VARCHAR(45) NULL,
  `any_debut` INT NULL,
  `total_voltes_rapides` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `f1History`.`pilot_usuari`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `f1History`.`pilot_usuari` (
  `pilot_id` INT NOT NULL,
  `log_user_id` INT NOT NULL,
  PRIMARY KEY (`pilot_id`, `log_user_id`),
  INDEX `fk_pilots_has_log_user_log_user1_idx` (`log_user_id` ASC),
  INDEX `fk_pilots_has_log_user_pilots1_idx` (`pilot_id` ASC),
  CONSTRAINT `fk_pilots_has_log_user_pilots1`
    FOREIGN KEY (`pilot_id`)
    REFERENCES `f1History`.`pilot` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pilots_has_log_user_log_user1`
    FOREIGN KEY (`log_user_id`)
    REFERENCES `f1History`.`log_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `f1History`.`escuderia_usuari`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `f1History`.`escuderia_usuari` (
  `scuderia_id` INT NOT NULL,
  `log_user_id` INT NOT NULL,
  PRIMARY KEY (`scuderia_id`, `log_user_id`),
  INDEX `fk_scuderia_has_log_user_log_user1_idx` (`log_user_id` ASC),
  INDEX `fk_scuderia_has_log_user_scuderia1_idx` (`scuderia_id` ASC),
  CONSTRAINT `fk_scuderia_has_log_user_scuderia1`
    FOREIGN KEY (`scuderia_id`)
    REFERENCES `f1History`.`scuderia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_scuderia_has_log_user_log_user1`
    FOREIGN KEY (`log_user_id`)
    REFERENCES `f1History`.`log_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `f1History`.`temporada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `f1History`.`temporada` (
  `any` YEAR NOT NULL,
  `pilot_campio` VARCHAR(45) NULL,
  `escuderia_campiona` VARCHAR(45) NULL,
  `reglametn` VARCHAR(1000) NULL,
  PRIMARY KEY (`any`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `f1History`.`carrito_has_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `f1History`.`carrito_has_products` (
  `carrito_id` INT NOT NULL,
  `producte_id` INT NOT NULL,
  `quantitat` INT NULL,
  PRIMARY KEY (`carrito_id`, `producte_id`),
  INDEX `fk_carrito_has_products_products1_idx` (`producte_id` ASC),
  INDEX `fk_carrito_has_products_carrito1_idx` (`carrito_id` ASC),
  CONSTRAINT `fk_carrito_has_products_carrito1`
    FOREIGN KEY (`carrito_id`)
    REFERENCES `f1History`.`carrito` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrito_has_products_products1`
    FOREIGN KEY (`producte_id`)
    REFERENCES `f1History`.`producte` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `f1History`.`circuit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `f1History`.`circuit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  `ciutat` VARCHAR(45) NULL,
  `longitud` VARCHAR(45) NULL,
  `curves` INT NULL,
  `zones_activacio_DRS` INT NULL,
  `zones_deteccio_DRS` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `f1History`.`carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `f1History`.`carrera` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom_carrera` VARCHAR(45) NULL,
  `data_carrera` DATE NULL,
  `posicio_final` VARCHAR(45) NULL,
  `circuit_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_carrera_circuit1_idx` (`circuit_id` ASC),
  CONSTRAINT `fk_carrera_circuit1`
    FOREIGN KEY (`circuit_id`)
    REFERENCES `f1History`.`circuit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `f1History`.`clasificacio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `f1History`.`clasificacio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pilot_id` INT NOT NULL,
  `carrera_id` INT NOT NULL,
  `punts` INT NULL COMMENT 'Esta tabla representa la clasificación de cada piloto por cada carrera de cada temporada\nLa información que se mostrará serán el ID del piloto, el ID de la carrera y los puntos obtenidos por parte del piloto',
  `sancions` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_clasificacio_pilot1_idx` (`pilot_id` ASC),
  INDEX `fk_clasificacio_carrera1_idx` (`carrera_id` ASC),
  CONSTRAINT `fk_clasificacio_pilot1`
    FOREIGN KEY (`pilot_id`)
    REFERENCES `f1History`.`pilot` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clasificacio_carrera1`
    FOREIGN KEY (`carrera_id`)
    REFERENCES `f1History`.`carrera` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `f1History`.`temporada_pilot_escuderia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `f1History`.`temporada_pilot_escuderia` (
  `temporada_any` YEAR NOT NULL,
  `pilot_id` INT NOT NULL,
  `scuderia_id` INT NOT NULL,
  `nom_cotxe` VARCHAR(45) NULL,
  `xasis` VARCHAR(45) NULL,
  `motor` VARCHAR(45) NULL,
  `numero_pilot` VARCHAR(45) NULL,
  INDEX `fk_temporada_pilot_escuderia_pilot1_idx` (`pilot_id` ASC),
  INDEX `fk_temporada_pilot_escuderia_scuderia1_idx` (`scuderia_id` ASC),
  PRIMARY KEY (`temporada_any`, `pilot_id`, `scuderia_id`),
  INDEX `fk_temporada_pilot_escuderia_temporada1_idx` (`temporada_any` ASC),
  CONSTRAINT `fk_temporada_pilot_escuderia_pilot1`
    FOREIGN KEY (`pilot_id`)
    REFERENCES `f1History`.`pilot` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_temporada_pilot_escuderia_scuderia1`
    FOREIGN KEY (`scuderia_id`)
    REFERENCES `f1History`.`scuderia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_temporada_pilot_escuderia_temporada1`
    FOREIGN KEY (`temporada_any`)
    REFERENCES `f1History`.`temporada` (`any`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
